### ISSUE TITLE
Update FamiTracker link

### ISSUE THREAD

**Issue by Gumball2415** [sirocyl/famitracker.org#1]
j0CC-FT was discontinued in August 2020, with version 0.6.3. Will the website continue to use j0CC with version updated to 0.6.3, or will it use the new Dn-FT fork, which picks up from j0CC?

**Comment by sirocyl** [comment]
Acknowledged, thank you - working on it now.

We will use the link to DN-FamiTracker, latest.

**Comment by sirocyl** [comment]
Alright, it's up to date. Thanks again for poking me about it. o7
